apiVersion: v1
kind: Service
metadata:
  name: kubernetes-learning
  labels:
    name: kubernetes-learning
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kubernetes-learning
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-learning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-learning
  template:
    metadata:
      labels:
        app: kubernetes-learning
    spec:
      containers:
        - name: my-kubernetes-learning
          image: tanujt1/kubernetes-learning:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: password