apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
data:
  password: cm9vdA== #root

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
data:
  database: dGVzdAo= #test

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
data:
  password: cGFzc3dvcmQ= #password
  username: dGFudWo= #tanuj

